/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Competition } from './models/competition';
export type { CompetitionStatus } from './models/competition-status';
export type { CreateCompetitionRequest } from './models/create-competition-request';
export type { CreateGroupRequest } from './models/create-group-request';
export type { CreateMatchdayRequest } from './models/create-matchday-request';
export type { CreateMatchRequest } from './models/create-match-request';
export type { CreateTeamRequest } from './models/create-team-request';
export type { GlobalRole } from './models/global-role';
export type { Group } from './models/group';
export type { GroupMembership } from './models/group-membership';
export type { GroupRole } from './models/group-role';
export type { LoginRequest } from './models/login-request';
export type { LoginResponse } from './models/login-response';
export type { Match } from './models/match';
export type { Matchday } from './models/matchday';
export type { MatchStage } from './models/match-stage';
export type { MatchStatus } from './models/match-status';
export type { Notification } from './models/notification';
export type { NotificationType } from './models/notification-type';
export type { Prediction } from './models/prediction';
export type { RankingEntry } from './models/ranking-entry';
export type { RegisterRequest } from './models/register-request';
export type { ScoringRule } from './models/scoring-rule';
export type { SubmitPredictionRequest } from './models/submit-prediction-request';
export type { Team } from './models/team';
export type { Theme } from './models/theme';
export type { UpdateCompetitionRequest } from './models/update-competition-request';
export type { UpdateMatchRequest } from './models/update-match-request';
export type { UpdateUserRequest } from './models/update-user-request';
export type { User } from './models/user';
