/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CompetitionStatus } from './competition-status';

/**
 * Each possible value of `CompetitionStatus`
 */
export const COMPETITION_STATUS: CompetitionStatus[] = [
  'DRAFT',
  'ACTIVE',
  'CLOSED',
  'ARCHIVED'
];