/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MatchStage } from '../models/match-stage';
export interface CreateMatchRequest {
  awayTeamId: number;
  homeTeamId: number;
  kickoffTime: string;
  stage?: MatchStage;
}
