/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GlobalRole } from './global-role';

/**
 * Each possible value of `GlobalRole`
 */
export const GLOBAL_ROLE: GlobalRole[] = [
  'USER',
  'ADMIN'
];