/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GroupRole } from '../models/group-role';
export interface GroupMembership {
  approved: boolean;
  groupId: number;
  id: number;
  joinedAt?: string;
  predictionsCount?: number;
  role: GroupRole;
  userId: number;
  username?: string;
}
