/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GroupRole } from './group-role';

/**
 * Each possible value of `GroupRole`
 */
export const GROUP_ROLE: GroupRole[] = [
  'MEMBER',
  'GROUP_ADMIN'
];