/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ManualBonus {
  awardedAt: string;
  awardedBy: string;
  id: number;
  points: number;
  reason?: string;
  userId: number;
  username: string;
}
