/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MatchStatus } from './match-status';

/**
 * Each possible value of `MatchStatus`
 */
export const MATCH_STATUS: MatchStatus[] = [
  'SCHEDULED',
  'LIVE',
  'FINISHED',
  'CANCELLED'
];