/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type MatchStage = 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | 'H' | 'I' | 'J' | 'K' | 'L' | 'ROUND_32' | 'ROUND_16' | 'ROUND_8' | 'SEMI_FINAL' | 'FINAL' | 'THIRD_PLACE';

