/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NotificationType } from '../models/notification-type';
export interface Notification {
  createdAt: string;
  id: number;
  message: string;
  read: boolean;
  title: string;
  type: NotificationType;
  userId: number;
}
