/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NotificationType } from './notification-type';

/**
 * Each possible value of `NotificationType`
 */
export const NOTIFICATION_TYPE: NotificationType[] = [
  'MATCHDAY_STARTS',
  'MISSING_PREDICTIONS',
  'REGISTRATION_APPROVED',
  'INVITATION_ACCEPTED'
];