/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RankingEntry {
  bonusPoints: number;
  exactPredictions: number;
  goalDifferencePredictions?: number;
  rank: number;
  tendencyPredictions: number;
  totalPoints: number;
  userId: number;
  username: string;
}
