/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Theme } from './theme';

/**
 * Each possible value of `Theme`
 */
export const THEME: Theme[] = [
  'LIGHT',
  'DARK',
  'SYSTEM'
];