/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MatchStatus } from '../models/match-status';
export interface UpdateMatchRequest {
  awayGoals?: number;
  awayTeamId?: number;
  homeGoals?: number;
  homeTeamId?: number;
  kickoffTime?: string;
  status?: MatchStatus;
}
