/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CompetitionStatus } from '../models/competition-status';
export interface UpdateCompetitionRequest {
  endDate?: string;
  name?: string;
  season?: string;
  startDate?: string;
  status?: CompetitionStatus;
}
