/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ManualBonus } from '../../models/manual-bonus';

export interface ListManualBonuses$Params {
  id: number;
}

export function listManualBonuses(http: HttpClient, rootUrl: string, params: ListManualBonuses$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ManualBonus>>> {
  const rb = new RequestBuilder(rootUrl, listManualBonuses.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ManualBonus>>;
    })
  );
}

listManualBonuses.PATH = '/groups/{id}/manual-bonuses';
