/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Notification } from '../../models/notification';

export interface MarkNotificationRead$Params {
  id: number;
}

export function markNotificationRead(http: HttpClient, rootUrl: string, params: MarkNotificationRead$Params, context?: HttpContext): Observable<StrictHttpResponse<Notification>> {
  const rb = new RequestBuilder(rootUrl, markNotificationRead.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Notification>;
    })
  );
}

markNotificationRead.PATH = '/notifications/{id}/read';
