/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateInvitationRequest } from '../../models/create-invitation-request';
import { Invitation } from '../../models/invitation';

export interface CreateInvitation$Params {
  id: number;
      body: CreateInvitationRequest
}

export function createInvitation(http: HttpClient, rootUrl: string, params: CreateInvitation$Params, context?: HttpContext): Observable<StrictHttpResponse<Invitation>> {
  const rb = new RequestBuilder(rootUrl, createInvitation.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Invitation>;
    })
  );
}

createInvitation.PATH = '/groups/{id}/invitations';
