/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Matchday } from '../../models/matchday';

export interface ListMatchdays$Params {
  competitionId: number;
}

export function listMatchdays(http: HttpClient, rootUrl: string, params: ListMatchdays$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Matchday>>> {
  const rb = new RequestBuilder(rootUrl, listMatchdays.PATH, 'get');
  if (params) {
    rb.query('competitionId', params.competitionId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Matchday>>;
    })
  );
}

listMatchdays.PATH = '/matchdays';
