/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateMatchdayRequest } from '../../models/create-matchday-request';
import { Matchday } from '../../models/matchday';

export interface UpdateMatchday$Params {
  id: number;
      body: CreateMatchdayRequest
}

export function updateMatchday(http: HttpClient, rootUrl: string, params: UpdateMatchday$Params, context?: HttpContext): Observable<StrictHttpResponse<Matchday>> {
  const rb = new RequestBuilder(rootUrl, updateMatchday.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Matchday>;
    })
  );
}

updateMatchday.PATH = '/matchdays/{id}';
