/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Match } from '../../models/match';

export interface ListMatchesByMatchday$Params {
  id: number;
}

export function listMatchesByMatchday(http: HttpClient, rootUrl: string, params: ListMatchesByMatchday$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Match>>> {
  const rb = new RequestBuilder(rootUrl, listMatchesByMatchday.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Match>>;
    })
  );
}

listMatchesByMatchday.PATH = '/matchdays/{id}/matches';
