/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Match } from '../../models/match';
import { UpdateMatchRequest } from '../../models/update-match-request';

export interface UpdateMatch$Params {
  id: number;
      body: UpdateMatchRequest
}

export function updateMatch(http: HttpClient, rootUrl: string, params: UpdateMatch$Params, context?: HttpContext): Observable<StrictHttpResponse<Match>> {
  const rb = new RequestBuilder(rootUrl, updateMatch.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Match>;
    })
  );
}

updateMatch.PATH = '/matches/{id}';
