/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RankingEntry } from '../../models/ranking-entry';

export interface GetGroupRankings$Params {
  id: number;
}

export function getGroupRankings(http: HttpClient, rootUrl: string, params: GetGroupRankings$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RankingEntry>>> {
  const rb = new RequestBuilder(rootUrl, getGroupRankings.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<RankingEntry>>;
    })
  );
}

getGroupRankings.PATH = '/groups/{id}/rankings';
