/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Group } from '../../models/group';

export interface ListGroups$Params {
  competitionId?: number;
}

export function listGroups(http: HttpClient, rootUrl: string, params?: ListGroups$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Group>>> {
  const rb = new RequestBuilder(rootUrl, listGroups.PATH, 'get');
  if (params) {
    rb.query('competitionId', params.competitionId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Group>>;
    })
  );
}

listGroups.PATH = '/groups';
