/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LegalNotice } from '../../models/legal-notice';

export interface UpdateLegalNotice$Params {
      body: LegalNotice
}

export function updateLegalNotice(http: HttpClient, rootUrl: string, params: UpdateLegalNotice$Params, context?: HttpContext): Observable<StrictHttpResponse<LegalNotice>> {
  const rb = new RequestBuilder(rootUrl, updateLegalNotice.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LegalNotice>;
    })
  );
}

updateLegalNotice.PATH = '/legal-notice';
