/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Competition } from '../../models/competition';
import { CreateCompetitionRequest } from '../../models/create-competition-request';

export interface CreateCompetition$Params {
      body: CreateCompetitionRequest
}

export function createCompetition(http: HttpClient, rootUrl: string, params: CreateCompetition$Params, context?: HttpContext): Observable<StrictHttpResponse<Competition>> {
  const rb = new RequestBuilder(rootUrl, createCompetition.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Competition>;
    })
  );
}

createCompetition.PATH = '/competitions';
