/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Competition } from '../../models/competition';

export interface GetCompetition$Params {
  id: number;
}

export function getCompetition(http: HttpClient, rootUrl: string, params: GetCompetition$Params, context?: HttpContext): Observable<StrictHttpResponse<Competition>> {
  const rb = new RequestBuilder(rootUrl, getCompetition.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Competition>;
    })
  );
}

getCompetition.PATH = '/competitions/{id}';
