/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ScoringRule } from '../../models/scoring-rule';

export interface GetScoringRules$Params {
  id: number;
}

export function getScoringRules(http: HttpClient, rootUrl: string, params: GetScoringRules$Params, context?: HttpContext): Observable<StrictHttpResponse<ScoringRule>> {
  const rb = new RequestBuilder(rootUrl, getScoringRules.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ScoringRule>;
    })
  );
}

getScoringRules.PATH = '/competitions/{id}/scoring-rules';
