/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Competition } from '../../models/competition';
import { UpdateCompetitionRequest } from '../../models/update-competition-request';

export interface UpdateCompetition$Params {
  id: number;
      body: UpdateCompetitionRequest
}

export function updateCompetition(http: HttpClient, rootUrl: string, params: UpdateCompetition$Params, context?: HttpContext): Observable<StrictHttpResponse<Competition>> {
  const rb = new RequestBuilder(rootUrl, updateCompetition.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Competition>;
    })
  );
}

updateCompetition.PATH = '/competitions/{id}';
