/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GroupMembership } from '../../models/group-membership';

export interface ApproveMember$Params {
  id: number;
  userId: number;
}

export function approveMember(http: HttpClient, rootUrl: string, params: ApproveMember$Params, context?: HttpContext): Observable<StrictHttpResponse<GroupMembership>> {
  const rb = new RequestBuilder(rootUrl, approveMember.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.path('userId', params.userId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GroupMembership>;
    })
  );
}

approveMember.PATH = '/groups/{id}/members/{userId}/approve';
