/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GroupMembership } from '../../models/group-membership';

export interface GetMyMemberships$Params {
}

export function getMyMemberships(http: HttpClient, rootUrl: string, params?: GetMyMemberships$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<GroupMembership>>> {
  const rb = new RequestBuilder(rootUrl, getMyMemberships.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<GroupMembership>>;
    })
  );
}

getMyMemberships.PATH = '/users/me/memberships';
