/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GroupMembership } from '../../models/group-membership';

export interface JoinGroup$Params {
  id: number;
}

export function joinGroup(http: HttpClient, rootUrl: string, params: JoinGroup$Params, context?: HttpContext): Observable<StrictHttpResponse<GroupMembership>> {
  const rb = new RequestBuilder(rootUrl, joinGroup.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GroupMembership>;
    })
  );
}

joinGroup.PATH = '/groups/{id}/join';
